package com.sunny.androidlasttestgreendao.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sunny.androidlasttestgreendao.bean.GreenDaoMess;

import com.sunny.androidlasttestgreendao.greendao.GreenDaoMessDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenDaoMessDaoConfig;

    private final GreenDaoMessDao greenDaoMessDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenDaoMessDaoConfig = daoConfigMap.get(GreenDaoMessDao.class).clone();
        greenDaoMessDaoConfig.initIdentityScope(type);

        greenDaoMessDao = new GreenDaoMessDao(greenDaoMessDaoConfig, this);

        registerDao(GreenDaoMess.class, greenDaoMessDao);
    }
    
    public void clear() {
        greenDaoMessDaoConfig.clearIdentityScope();
    }

    public GreenDaoMessDao getGreenDaoMessDao() {
        return greenDaoMessDao;
    }

}
